const PROVINCES_AT = [
    {
        name: "Burgenland",
        shortName: "Burgenland",
        code: "B",
        counties: [
            "Eisenstadt",
            "Eisenstadt-Umgebung",
            "Güssing",
            "Jennersdorf",
            "Mattersburg",
            "Neusiedl am See",
            "Oberpullendorf",
            "Oberwart",
            "Rust",
        ],
    },
    {
        name: "Kärnten",
        shortName: "Kärnten",
        code: "K",
        counties: [
            "Hermagor",
            "Klagenfurt",
            "Klagenfurt-Land",
            "Sankt Veit an der Glan",
            "Spittal an der Drau",
            "Villach",
            "Villach-Land",
            "Völkermarkt",
            "Wolfsberg",
        ],
    },
    {
        name: "Niederösterreich",
        shortName: "Niederösterreich",
        code: "NÖ",
        counties: [
            "Amstetten",
            "Baden",
            "Bruck an der Leitha",
            "Gänserndorf",
            "Gmünd",
            "Hollabrunn",
            "Horn",
            "Korneuburg",
            "Krems an der Donau",
            "Krems-Land",
            "Lilienfeld",
            "Melk",
            "Mistelbach",
            "Mödling",
            "Neunkirchen",
            "Sankt Pölten",
            "Sankt Pölten-Land",
            "Scheibbs",
            "Tulln",
            "Waidhofen an der Thaya",
            "Waidhofen an der Ybbs",
            "Wiener Neustadt",
            "Wiener Neustadt-Land",
            "Zwettl",
        ],
    },
    {
        name: "Oberösterreich",
        shortName: "Oberösterreich",
        code: "OÖ",
        counties: [
            "Braunau am Inn",
            "Eferding",
            "Freistadt",
            "Gmunden",
            "Grieskirchen",
            "Kirchdorf an der Krems",
            "Linz",
            "Linz-Land",
            "Perg",
            "Ried im Innkreis",
            "Rohrbach",
            "Schärding",
            "Steyr",
            "Steyr-Land",
            "Urfahr-Umgebung",
            "Vöcklabruck",
            "Wels",
            "Wels-Land",
        ],
    },
    {
        name: "Salzburg",
        shortName: "Salzburg",
        code: "S",
        counties: ["Hallein", "Salzburg", "Salzburg-Umgebung", "Sankt Johann im Pongau", "Tamsweg", "Zell am See"],
    },
    {
        name: "Steiermark",
        shortName: "Steiermark",
        code: "ST",
        counties: [
            "Bruck-Mürzzuschlag",
            "Deutschlandsberg",
            "Graz",
            "Graz-Umgebung",
            "Hartberg-Fürstenfeld",
            "Leibnitz",
            "Leoben",
            "Liezen",
            "Murau",
            "Murtal",
            "Südoststeiermark",
            "Voitsberg",
            "Weiz",
        ],
    },
    {
        name: "Tirol",
        shortName: "Tirol",
        code: "T",
        counties: ["Imst", "Innsbruck", "Innsbruck-Land", "Kitzbühel", "Kufstein", "Landeck", "Lienz", "Reutte", "Schwaz"],
    },
    {
        name: "Vorarlberg",
        shortName: "Vorarlberg",
        code: "V",
        counties: ["Bludenz", "Bregenz", "Dornbirn", "Feldkirch"],
    },
    {
        name: "Wien",
        shortName: "Wien",
        code: "W",
        counties: ["Wien"],
    },
];

export default PROVINCES_AT;

export const COUNTIES_AT = PROVINCES_AT.reduce((acc, province) => {
    return [...acc, ...province.counties];
}, []);
