const PROVINCES_AT = [
    {
        name: "Burgenland",
        shortName: "Burgenland",
        code: "B",
        counties: ["Eisenstadt", "Güssing", "Jennersdorf", "Mattersburg", "Neusiedl am See", "Oberpullendorf", "Oberwart", "Rust"],
    },
    {
        name: "Kärnten",
        shortName: "Kärnten",
        code: "K",
        counties: ["Feldkirchen", "Hermagor", "Klagenfurt", "Sankt Veit an der Glan", "Spittal an der Drau", "Villach", "Völkermarkt", "Wolfsberg"],
    },
    {
        name: "Niederösterreich",
        shortName: "Niederösterreich",
        code: "NÖ",
        counties: [
            "Amstetten",
            "Baden",
            "Bruck an der Leitha",
            "Gänserndorf",
            "Gmünd",
            "Hollabrunn",
            "Horn",
            "Korneuburg",
            "Krems",
            "Lilienfeld",
            "Melk",
            "Mistelbach",
            "Mödling",
            "Neunkirchen",
            "St. Pölten",
            "Scheibbs",
            "Tulln an der Donau",
            "Waidhofen an der Thaya",
            "Wiener Neustadt",
            "Zwettl",
        ],
    },
    {
        name: "Oberösterreich",
        shortName: "Oberösterreich",
        code: "OÖ",
        counties: [
            "Braunau",
            "Eferding",
            "Freistadt",
            "Gmunden",
            "Grieskirchen",
            "Kirchdorf",
            "Linz",
            "Perg",
            "Ried",
            "Rohrbach",
            "Schärding",
            "Steyr",
            "Urfahr-Umgebung",
            "Vöcklabruck",
            "Wels",
        ],
    },
    {
        name: "Salzburg",
        shortName: "Salzburg",
        code: "S",
        counties: ["Hallein", "Salzburg", "Sankt Johann im Pongau", "Tamsweg", "Zell am See"],
    },
    {
        name: "Steiermark",
        shortName: "Steiermark",
        code: "ST",
        counties: [
            "Bruck-Mürzzuschlag",
            "Deutschlandsberg",
            "Graz",
            "Hartberg-Fürstenfeld",
            "Leibnitz",
            "Leoben",
            "Liezen",
            "Murau",
            "Murtal",
            "Südoststeiermark",
            "Voitsberg",
            "Weiz",
        ],
    },
    {
        name: "Tirol",
        shortName: "Tirol",
        code: "T",
        counties: ["Imst", "Innsbruck", "Kitzbühel", "Kufstein", "Landeck", "Lienz", "Reutte", "Schwaz"],
    },
    {
        name: "Vorarlberg",
        shortName: "Vorarlberg",
        code: "V",
        counties: ["Bludenz", "Bregenz", "Dornbirn", "Feldkirch"],
    },
    {
        name: "Wien",
        shortName: "Wien",
        code: "W",
        counties: ["Wien"],
    },
];

export default PROVINCES_AT;

export const COUNTIES_AT = PROVINCES_AT.reduce((acc, province) => {
    return [...acc, ...province.counties];
}, []);
