const PROVINCES_HU = [
    {
        name: "Bács-Kiskun megye",
        shortName: "Bács-Kiskun",
        code: "BK",
        counties: [
            "Baja",
            "Bácsalmás",
            "Dunaföldvár",
            "Dunavecse",
            "Fülöpszállás",
            "Izsák",
            "Jánoshalma",
            "Kalocsa",
            "Kecskemét",
            "Kiskőrös",
            "Kiskunfélegyháza",
            "Kiskunhalas",
            "Kiskunmajsa",
            "Kunszentmiklós",
            "Lakitelek",
            "Orgovány",
            "Solt",
            "Szabadszállás",
            "Tiszakécske",
            "Tompa",
        ],
    },
    {
        name: "Baranya megye",
        shortName: "Baranya",
        code: "BA",
        counties: ["Bóly", "Harkány", "Komló", "Mohács", "Pécs", "Pécsvárad", "Sásd", "Sellye", "Siklós", "Szentlőrinc", "Villány"],
    },
    {
        name: "Békés megye",
        shortName: "Békés",
        code: "BE",
        counties: [
            "Battonya",
            "Békés",
            "Békéscsaba",
            "Dévaványa",
            "Elek",
            "Gyomaendrőd",
            "Gyula",
            "Kondoros",
            "Mezőberény",
            "Mezőhegyes",
            "Mezőkovácsháza",
            "Orosháza",
            "Sarkad",
            "Szarvas",
            "Tótkomlós",
        ],
    },
    {
        name: "Borsod-Abaúj-Zemplén megye",
        shortName: "Borsod-Abaúj-Zemplén",
        code: "BZ",
        counties: [
            "Abaújszántó",
            "Bodrogkeresztúr",
            "Bőcs",
            "Cigánd",
            "Edelény",
            "Encs",
            "Gönc",
            "Hatvan",
            "Kazincbarcika",
            "Mezőcsát",
            "Mezőkövesd",
            "Miskolc",
            "Ózd",
            "Putnok",
            "Sárospatak",
            "Sátoraljaújhely",
            "Szerencs",
            "Szikszó",
            "Tarcal",
            "Tiszaújváros",
            "Tokaj",
        ],
    },
    {
        name: "Budapest",
        shortName: "Budapest",
        code: "BU",
        counties: ["Budapest"],
    },
    {
        name: "Csongrád-Csanád megye",
        shortName: "Csongrád-Csanád",
        code: "CS",
        counties: ["Csongrád-Bokros", "Hódmezővásárhely", "Kistelek", "Makó", "Mindszent", "Mórahalom", "Szentes", "Szeged"],
    },
    {
        name: "Fejér megye",
        shortName: "Fejér",
        code: "FE",
        counties: [
            "Aba",
            "Adony",
            "Bicske",
            "Dunaújváros",
            "Enying",
            "Ercsi",
            "Gárdony",
            "Martonvásár",
            "Mór",
            "Pusztaszabolcs",
            "Sárbogárd",
            "Székesfehérvár",
            "Velence",
        ],
    },
    {
        name: "Győr-Moson-Sopron megye",
        shortName: "Győr-Moson-Sopron",
        code: "GS",
        counties: ["Csorna", "Fertőd", "Győr", "Kapuvár", "Mosonmagyaróvár", "Pannonhalma", "Sopron", "Tét"],
    },
    {
        name: "Hajdú-Bihar megye",
        shortName: "Hajdú-Bihar",
        code: "HB",
        counties: [
            "Balmazújváros",
            "Berettyóújfalu",
            "Debrecen",
            "Hajdúböszörmény",
            "Hajdúdorog",
            "Hajdúhadház",
            "Hajdúnánás",
            "Hajdúsámson",
            "Hajdúszoboszló",
            "Létavértes",
            "Nádudvar",
            "Püspökladány",
            "Téglás",
            "Újfehértó",
        ],
    },
    {
        name: "Heves megye",
        shortName: "Heves",
        code: "HE",
        counties: ["Bélapátfalva", "Eger", "Füzesabony", "Gyöngyös", "Hatvan", "Heves", "Pétervására", "Recsk", "Tarnalelesz"],
    },
    {
        name: "Jász-Nagykun-Szolnok megye",
        shortName: "Jász-Nagykun-Szolnok",
        code: "JN",
        counties: [
            "Jászapáti",
            "Jászberény",
            "Karcag",
            "Kenderes",
            "Kisújszállás",
            "Kunhegyes",
            "Kunszentmárton",
            "Mezőtúr",
            "Szolnok",
            "Tiszafüred",
            "Törökszentmiklós",
            "Túrkeve",
        ],
    },
    {
        name: "Komárom-Esztergom megye",
        shortName: "Komárom-Esztergom",
        code: "KE",
        counties: ["Ács", "Almásfüzitő", "Bábolna", "Dorog", "Esztergom", "Kisbér", "Komárom", "Lábatlan", "Oroszlány", "Tata", "Tatabánya"],
    },
    {
        name: "Nógrád megye",
        shortName: "Nógrád",
        code: "NO",
        counties: ["Balassagyarmat", "Bátonyterenye", "Bercel", "Cervenica", "Pásztó", "Rétság", "Salgótarján", "Szécsény"],
    },
    {
        name: "Pest megye",
        shortName: "Pest",
        code: "PE",
        counties: [
            "Abony",
            "Albertirsa",
            "Aszód",
            "Budakalász",
            "Budakeszi",
            "Budaörs",
            "Cegléd",
            "Dabas",
            "Délegyháza",
            "Dunaharaszti",
            "Dunakeszi",
            "Érd",
            "Fót",
            "Gödöllő",
            "Gyál",
            "Halásztelek",
            "Isaszeg",
            "Jászkarajenő",
            "Kerepes",
            "Kistarcsa",
            "Monor",
            "Nagykáta",
            "Nagykőrös",
            "Pécel",
            "Pilis",
            "Piliscsaba",
            "Pilisszentiván",
            "Pilisszentkereszt",
            "Pomáz",
            "Ráckeve",
            "Récse",
            "Santarém",
            "Soroksár",
            "Százhalombatta",
            "Szentendre",
            "Szigetszentmiklós",
            "Szob",
            "Törökbálint",
            "Újhartyán",
            "Újpest",
            "Vecsés",
            "Visegrád",
        ],
    },
    {
        name: "Somogy megye",
        shortName: "Somogy",
        code: "SO",
        counties: [
            "Balatonboglár",
            "Balatonlelle",
            "Barcs",
            "Csurgó",
            "Fonyód",
            "Kaposvár",
            "Lengyeltóti",
            "Marcali",
            "Nagyatád",
            "Nagykanizsa",
            "Siófok",
            "Tab",
        ],
    },
    {
        name: "Szabolcs-Szatmár-Bereg megye",
        shortName: "Szabolcs-Szatmár-Bereg",
        code: "SZ",
        counties: [
            "Baktalórántháza",
            "Fehérgyarmat",
            "Ibrány",
            "Kemecse",
            "Kisvárda",
            "Mátészalka",
            "Nagyhalász",
            "Nyírbátor",
            "Nyíregyháza",
            "Nyírlugos",
            "Nyírtelek",
            "Tiszavasvári",
            "Vásárosnamény",
            "Záhony",
        ],
    },
    {
        name: "Tolna megye",
        shortName: "Tolna",
        code: "TO",
        counties: ["Bonyhád", "Dombóvár", "Dunaföldvár", "Paks", "Szekszárd", "Tamási"],
    },
    {
        name: "Vas megye",
        shortName: "Vas",
        code: "VA",
        counties: ["Celldömölk", "Csepreg", "Körmend", "Kőszeg", "Répcelak", "Sárvár", "Szentgotthárd", "Szombathely", "Vasvár"],
    },
    {
        name: "Veszprém megye",
        shortName: "Veszprém",
        code: "VE",
        counties: ["Ajka", "Balatonalmádi", "Balatonfüred", "Devecser", "Herend", "Pápa", "Sümeg", "Tapolca", "Várpalota", "Veszprém", "Zirc"],
    },
    {
        name: "Zala megye",
        shortName: "Zala",
        code: "ZA",
        counties: ["Hévíz", "Keszthely", "Lenti", "Letenye", "Nagykanizsa", "Nova", "Zalaegerszeg", "Zalaszentgrót"],
    },
];

export default PROVINCES_HU;

export const COUNTIES_HU = PROVINCES_HU.reduce((acc, province) => {
    return [...acc, ...province.counties];
}, []);
