const PROVINCES_PL = [
    {
        name: "Dolnośląskie",
        shortName: "Dolnośląskie",
        code: "DS",
        counties: [
            "Bolesławiec",
            "Dzierżoniów",
            "Głogów",
            "Góra",
            "Jawor",
            "Jelenia Góra",
            "Kamienna Góra",
            "Kłodzko",
            "Legnica",
            "Lubań",
            "Lubin",
            "Lwówek Śląski",
            "Milicz",
            "Oleśnica",
            "Oława",
            "Polkowice",
            "Strzelin",
            "Świdnica",
            "Trzebnica",
            "Wałbrzych",
            "Wołów",
            "Wrocław",
            "Ząbkowice Śląskie",
            "Zgorzelec",
            "Złotoryja",
        ],
    },
    {
        name: "Kujawsko-pomorskie",
        shortName: "Kujawsko-pomorskie",
        code: "KP",
        counties: [
            "Aleksandrów Kujawski",
            "Brodnica",
            "Bydgoszcz",
            "Chełmno",
            "Golub-Dobrzyń",
            "Grudziądz",
            "Inowrocław",
            "Lipno",
            "Mogilno",
            "Nakło nad Notecią",
            "Radziejów",
            "Rypin",
            "Sępólno Krajeńskie",
            "Świecie",
            "Toruń",
            "Tuchola",
            "Wąbrzeźno",
            "Włocławek",
            "Żnin",
        ],
    },
    {
        name: "Lubelskie",
        shortName: "Lubelskie",
        code: "LU",
        counties: [
            "Biała Podlaska",
            "Biłgoraj",
            "Chełm",
            "Hrubieszów",
            "Janów Lubelski",
            "Kraśnik",
            "Krasnystaw",
            "Lubartów",
            "Lublin",
            "Łęczna",
            "Łuków",
            "Opole Lubelskie",
            "Parczew",
            "Puławy",
            "Radzyń Podlaski",
            "Ryki",
            "Świdnik",
            "Tomaszów Lubelski",
            "Włodawa",
            "Zamość",
        ],
    },
    {
        name: "Lubuskie",
        shortName: "Lubuskie",
        code: "LB",
        counties: [
            "Gorzów Wielkopolski",
            "Krosno Odrzańskie",
            "Międzyrzecz",
            "Nowa Sól",
            "Słubice",
            "Strzelce Krajeńskie",
            "Sulęcin",
            "Świebodzin",
            "Wschowa",
            "Zielona Góra",
            "Żagań",
            "Żary",
        ],
    },
    {
        name: "Łódzkie",
        shortName: "Łódzkie",
        code: "LD",
        counties: [
            "Bełchatów",
            "Brzeziny",
            "Kutno",
            "Łask",
            "Łęczyca",
            "Łódź",
            "Łowicz",
            "Opoczno",
            "Pabianice",
            "Pajęczno",
            "Piotrków Trybunalski",
            "Poddębice",
            "Radomsko",
            "Rawa Mazowiecka",
            "Sieradz",
            "Skierniewice",
            "Tomaszów Mazowiecki",
            "Wieluń",
            "Wieruszów",
            "Zgierz",
            "Zduńska Wola",
        ],
    },
    {
        name: "Małopolskie",
        shortName: "Małopolskie",
        code: "MA",
        counties: [
            "Bochnia",
            "Brzesko",
            "Chrzanów",
            "Dąbrowa Tarnowska",
            "Gorlice",
            "Kraków",
            "Limanowa",
            "Miechów",
            "Myślenice",
            "Nowy Sącz",
            "Nowy Targ",
            "Olkusz",
            "Oświęcim",
            "Proszowice",
            "Sucha Beskidzka",
            "Tarnów",
            "Tatrzański",
            "Wadowice",
            "Wieliczka",
        ],
    },
    {
        name: "Mazowieckie",
        shortName: "Mazowieckie",
        code: "MZ",
        counties: [
            "Białobrzegi",
            "Ciechanów",
            "Garwolin",
            "Gostynin",
            "Grodzisk Mazowiecki",
            "Grójec",
            "Kozienice",
            "Legionowo",
            "Lipsko",
            "Łosice",
            "Maków",
            "Mińsk Mazowiecki",
            "Mława",
            "Nowy Dwór Mazowiecki",
            "Ostrołęka",
            "Ostrów Mazowiecka",
            "Otwock",
            "Piaseczno",
            "Płock",
            "Płońsk",
            "Przasnysz",
            "Pruszków",
            "Pułtusk",
            "Radom",
            "Siedlce",
            "Sierpc",
            "Sochaczew",
            "Sokołów Podlaski",
            "Szydłowiec",
            "Warszawa",
            "Węgrów",
            "Wołomin",
            "Wyszków",
            "Zwoleń",
            "Żuromin",
            "Żyrardów",
        ],
    },
    {
        name: "Opolskie",
        shortName: "Opolskie",
        code: "OP",
        counties: [
            "Brzeg",
            "Głubczyce",
            "Kędzierzyn-Koźle",
            "Kluczbork",
            "Krapkowice",
            "Namysłów",
            "Nysa",
            "Olesno",
            "Opole",
            "Prudnik",
            "Strzelce Opolskie",
        ],
    },
    {
        name: "Podkarpackie",
        shortName: "Podkarpackie",
        code: "PK",
        counties: [
            "Bieszczady",
            "Brzozów",
            "Dębica",
            "Jarosław",
            "Jasło",
            "Kolbuszowa",
            "Krosno",
            "Leżajsk",
            "Lubaczów",
            "Łańcut",
            "Mielec",
            "Niżański",
            "Przemyśl",
            "Przeworsk",
            "Ropczyce-Sędziszów",
            "Rzeszów",
            "Sanok",
            "Stalowa Wola",
            "Strzyżów",
            "Tarnobrzeg",
        ],
    },
    {
        name: "Podlaskie",
        shortName: "Podlaskie",
        code: "PD",
        counties: [
            "Augustów",
            "Białystok",
            "Bielsk Podlaski",
            "Grajewo",
            "Hajnówka",
            "Kolno",
            "Łomża",
            "Mońki",
            "Sejny",
            "Siemiatycze",
            "Sokółka",
            "Suwałki",
            "Wysokie Mazowieckie",
            "Zambrów",
        ],
    },
    {
        name: "Pomorskie",
        shortName: "Pomorskie",
        code: "PM",
        counties: [
            "Bytów",
            "Chojnice",
            "Człuchów",
            "Gdańsk",
            "Gdynia",
            "Kartuzy",
            "Kościerzyna",
            "Kwidzyn",
            "Lębork",
            "Malbork",
            "Nowy Dwór Gdański",
            "Pruszcz Gdański",
            "Słupsk",
            "Sopot",
            "Starogard Gdański",
            "Tczew",
            "Wejherowo",
        ],
    },
    {
        name: "Śląskie",
        shortName: "Śląskie",
        code: "SL",
        counties: [
            "Bielsko-Biała",
            "Bieruń-Lędziny",
            "Bytom",
            "Chorzów",
            "Cieszyn",
            "Częstochowa",
            "Dąbrowa Górnicza",
            "Gliwice",
            "Jaworzno",
            "Katowice",
            "Kłobuck",
            "Lubliniec",
            "Mikołów",
            "Mysłowice",
            "Myszków",
            "Piekary Śląskie",
            "Pszczyna",
            "Racibórz",
            "Ruda Śląska",
            "Rybnik",
            "Siemianowice Śląskie",
            "Sosnowiec",
            "Świętochłowice",
            "Tarnowskie Góry",
            "Tychy",
            "Wodzisław Śląski",
            "Zabrze",
            "Zawiercie",
            "Żory",
            "Żywiec",
        ],
    },
    {
        name: "Świętokrzyskie",
        shortName: "Świętokrzyskie",
        code: "SK",
        counties: [
            "Busko-Zdrój",
            "Jędrzejów",
            "Kazimierza Wielka",
            "Kielce",
            "Końskie",
            "Opatów",
            "Ostrowiec Świętokrzyski",
            "Pińczów",
            "Sandomierz",
            "Skarżysko-Kamienna",
            "Starachowice",
            "Staszów",
            "Włoszczowa",
        ],
    },
    {
        name: "Warmińsko-mazurskie",
        shortName: "Warmińsko-mazurskie",
        code: "WM",
        counties: [
            "Bartoszyce",
            "Braniewo",
            "Działdowo",
            "Elbląg",
            "Ełk",
            "Giżycko",
            "Gołdap",
            "Iława",
            "Kętrzyn",
            "Lidzbark Warmiński",
            "Mrągowo",
            "Nidzica",
            "Nowe Miasto Lubawskie",
            "Olecko",
            "Olsztyn",
            "Ostróda",
            "Pisz",
            "Szczytno",
            "Węgorzewo",
        ],
    },
    {
        name: "Wielkopolskie",
        shortName: "Wielkopolskie",
        code: "WP",
        counties: [
            "Chodzież",
            "Czarnków-Trzcianka",
            "Gniezno",
            "Gostyń",
            "Grodzisk Wielkopolski",
            "Jarocin",
            "Kalisz",
            "Kępno",
            "Koło",
            "Konin",
            "Kościan",
            "Krotoszyn",
            "Leszno",
            "Międzychód",
            "Nowy Tomyśl",
            "Oborniki",
            "Ostrów Wielkopolski",
            "Ostrzeszów",
            "Piła",
            "Pleszew",
            "Poznań",
            "Rawicz",
            "Słupca",
            "Szamotuły",
            "Śrem",
            "Środa Wielkopolska",
            "Turek",
            "Wągrowiec",
            "Wolsztyn",
            "Września",
            "Złotów",
        ],
    },
    {
        name: "Zachodniopomorskie",
        shortName: "Zachodniopomorskie",
        code: "ZP",
        counties: [
            "Białogard",
            "Choszczno",
            "Drawsko Pomorskie",
            "Goleniów",
            "Gryfice",
            "Gryfino",
            "Kamień Pomorski",
            "Kołobrzeg",
            "Koszalin",
            "Łobez",
            "Myślibórz",
            "Police",
            "Pyrzyce",
            "Sławno",
            "Stargard",
            "Szczecin",
            "Szczecinek",
            "Świdwin",
            "Wałcz",
            "Węgorzyno",
        ],
    },
];

export default PROVINCES_PL;

export const COUNTIES_PL = PROVINCES_PL.reduce((acc, province) => {
    return [...acc, ...province.counties];
}, []);
