export const provincesList = [
    "Hlavní město Praha",
    "Jihomoravský kraj",
    "Jihočeský kraj",
    "Karlovarský kraj",
    "Kraj Vysočina",
    "Královéhradecký kraj",
    "Liberecký kraj",
    "Moravskoslezský kraj",
    "Olomoucký kraj",
    "Pardubický kraj",
    "Plzeňský kraj",
    "Středočeský kraj",
    "Zlínský kraj",
    "Ústecký kraj",
];

export const provincesShortList = [
    "Jihomoravský",
    "Jihočeský",
    "Karlovarský",
    "Královéhradecký",
    "Liberecký",
    "Moravskoslezský",
    "Olomoucký",
    "Pardubický",
    "Plzeňský",
    "Praha",
    "Středočeský",
    "Vysočina",
    "Zlínský",
    "Ústecký",
];

export const provincesMappedCounty: { [char: string]: string } = {
    Benešov: "Středočeský kraj",
    Beroun: "Středočeský kraj",
    Blansko: "Jihomoravský kraj",
    "Brno-město": "Jihomoravský kraj",
    "Brno-venkov": "Jihomoravský kraj",
    Bruntál: "Moravskoslezský kraj",
    Břeclav: "Jihomoravský kraj",
    "Česká Lípa": "Liberecký kraj",
    "České Budějovice": "Jihočeský kraj",
    "Český Krumlov": "Jihočeský kraj",
    Děčín: "Ústecký kraj",
    Domažlice: "Plzeňský kraj",
    "Frýdek-Místek": "Moravskoslezský kraj",
    "Havlíčkův Brod": "Kraj Vysočina",
    Hodonín: "Jihomoravský kraj",
    "Hradec Králové": "Královéhradecký kraj",
    Cheb: "Karlovarský kraj",
    Chomutov: "Ústecký kraj",
    Chrudim: "Pardubický kraj",
    "Jablonec nad Nisou": "Liberecký kraj",
    Jeseník: "Olomoucký kraj",
    Jičín: "Královéhradecký kraj",
    Jihlava: "Kraj Vysočina",
    "Jindřichův Hradec": "Jihočeský kraj",
    "Karlovy Vary": "Karlovarský kraj",
    Karviná: "Moravskoslezský kraj",
    Kladno: "Středočeský kraj",
    Klatovy: "Plzeňský kraj",
    Kolín: "Středočeský kraj",
    Kroměříž: "Zlínský kraj",
    "Kutná Hora": "Středočeský kraj",
    Liberec: "Liberecký kraj",
    Litoměřice: "Ústecký kraj",
    Louny: "Ústecký kraj",
    Mělník: "Středočeský kraj",
    "Mladá Boleslav": "Středočeský kraj",
    Most: "Ústecký kraj",
    Náchod: "Královéhradecký kraj",
    "Nový Jičín": "Moravskoslezský kraj",
    Nymburk: "Středočeský kraj",
    Olomouc: "Olomoucký kraj",
    Opava: "Moravskoslezský kraj",
    "Ostrava-město": "Moravskoslezský kraj",
    Pardubice: "Pardubický kraj",
    Pelhřimov: "Kraj Vysočina",
    Písek: "Jihočeský kraj",
    "Plzeň-jih": "Plzeňský kraj",
    "Plzeň-město": "Plzeňský kraj",
    "Plzeň-sever": "Plzeňský kraj",
    Praha: "Hlavní město Praha",
    "Praha-východ": "Středočeský kraj",
    "Praha-západ": "Středočeský kraj",
    Prachatice: "Jihočeský kraj",
    Prostějov: "Olomoucký kraj",
    Přerov: "Olomoucký kraj",
    Příbram: "Středočeský kraj",
    Rakovník: "Středočeský kraj",
    Rokycany: "Plzeňský kraj",
    "Rychnov nad Kněžnou": "Královéhradecký kraj",
    Semily: "Liberecký kraj",
    Sokolov: "Karlovarský kraj",
    Strakonice: "Jihočeský kraj",
    Svitavy: "Pardubický kraj",
    Šumperk: "Olomoucký kraj",
    Tachov: "Plzeňský kraj",
    Tábor: "Jihočeský kraj",
    Teplice: "Ústecký kraj",
    Trutnov: "Královéhradecký kraj",
    Třebíč: "Kraj Vysočina",
    "Uherské Hradiště": "Zlínský kraj",
    "Ústí nad Labem": "Ústecký kraj",
    "Ústí nad Orlicí": "Pardubický kraj",
    Vsetín: "Zlínský kraj",
    Vyškov: "Jihomoravský kraj",
    Zlín: "Zlínský kraj",
    Znojmo: "Jihomoravský kraj",
    "Žďár nad Sázavou": "Kraj Vysočina",
};

export const countyList = [
    "Okres Brno-město",
    "Okres Brno-venkov",
    "Okres Bruntál",
    "Okres Břeclav",
    "Okres Česká Lípa",
    "Okres České Budějovice",
    "Okres Český Krumlov",
    "Okres Děčín",
    "Okres Domažlice",
    "Okres Frýdek-Místek",
    "Okres Havlíčkův Brod",
    "Okres Hodonín",
    "Okres Hradec Králové",
    "Okres Cheb",
    "Okres Chomutov",
    "Okres Chrudim",
    "Okres Jablonec nad Nisou",
    "Okres Jeseník",
    "Okres Jičín",
    "Okres Jihlava",
    "Okres Jindřichův Hradec",
    "Okres Karlovy Vary",
    "Okres Karviná",
    "Okres Kladno",
    "Okres Klatovy",
    "Okres Kolín",
    "Okres Kroměříž",
    "Okres Kutná Hora",
    "Okres Liberec",
    "Okres Litoměřice",
    "Okres Louny",
    "Okres Mělník",
    "Okres Mladá Boleslav",
    "Okres Most",
    "Okres Náchod",
    "Okres Nový Jičín",
    "Okres Nymburk",
    "Okres Olomouc",
    "Okres Opava",
    "Okres Ostrava-město",
    "Okres Pardubice",
    "Okres Pelhřimov",
    "Okres Písek",
    "Okres Plzeň-jih",
    "Okres Plzeň-město",
    "Okres Plzeň-sever",
    "Hlavní město Praha",
    "Okres Praha-východ",
    "Okres Praha-západ",
    "Okres Prachatice",
    "Okres Prostějov",
    "Okres Přerov",
    "Okres Příbram",
    "Okres Rakovník",
    "Okres Rokycany",
    "Okres Rychnov nad Kněžnou",
    "Okres Semily",
    "Okres Sokolov",
    "Okres Strakonice",
    "Okres Svitavy",
    "Okres Šumperk",
    "Okres Tábor",
    "Okres Tachov",
    "Okres Teplice",
    "Okres Trutnov",
    "Okres Třebíč",
    "Okres Uherské Hradiště",
    "Okres Ústí nad Labem",
    "Okres Ústí nad Orlicí",
    "Okres Vsetín",
    "Okres Vyškov",
    "Okres Zlín",
    "Okres Znojmo",
    "Okres Žďár nad Sázavou",
];

export const countyShortList = [
    "Brno-město",
    "Brno-venkov",
    "Bruntál",
    "Břeclav",
    "Česká Lípa",
    "České Budějovice",
    "Český Krumlov",
    "Děčín",
    "Domažlice",
    "Frýdek-Místek",
    "Havlíčkův Brod",
    "Hodonín",
    "Hradec Králové",
    "Cheb",
    "Chomutov",
    "Chrudim",
    "Jablonec nad Nisou",
    "Jeseník",
    "Jičín",
    "Jihlava",
    "Jindřichův Hradec",
    "Karlovy Vary",
    "Karviná",
    "Kladno",
    "Klatovy",
    "Kolín",
    "Kroměříž",
    "Kutná Hora",
    "Liberec",
    "Litoměřice",
    "Louny",
    "Mělník",
    "Mladá Boleslav",
    "Most",
    "Náchod",
    "Nový Jičín",
    "Nymburk",
    "Olomouc",
    "Opava",
    "Ostrava-město",
    "Pardubice",
    "Pelhřimov",
    "Písek",
    "Plzeň-jih",
    "Plzeň-město",
    "Plzeň-sever",
    "Praha",
    "Praha-východ",
    "Praha-západ",
    "Prachatice",
    "Prostějov",
    "Přerov",
    "Příbram",
    "Rakovník",
    "Rokycany",
    "Rychnov nad Kněžnou",
    "Semily",
    "Sokolov",
    "Strakonice",
    "Svitavy",
    "Šumperk",
    "Tábor",
    "Tachov",
    "Teplice",
    "Trutnov",
    "Třebíč",
    "Uherské Hradiště",
    "Ústí nad Labem",
    "Ústí nad Orlicí",
    "Vsetín",
    "Vyškov",
    "Zlín",
    "Znojmo",
    "Žďár nad Sázavou",
];

export const materials = ["dřevo", "kámen", "železo", "kov", "ocel", "beton", "zdivo", "přírodní"];
export const towerType = ["rozhledna", "pozorovatelna", "městská věž", "kostelní věž", "hradní věž", "zámecká věž", "přírodní vyhlídka"];
export const towerTypeURL = ["rozhledna", "pozorovatelna", "mestska_vez", "hradni_vez", "zamecka_vez", "prirodni_vyhlidka", "kostelni_vez"];
export const towerTypeMappedUrl = {
    rozhledna: "rozhledna",
    pozorovatelna: "pozorovatelna",
    "městská věž": "mestska_vez",
    "hradní věž": "hradni_vez",
    "zámecká věž": "zamecka_vez",
    "přírodní vyhlídka": "prirodni_vyhlidka",
    "kostelní věž": "kostelni_vez",
};

export const MONTHS_CZECH = ["Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec"];
export const MONTHS_CZECH_4 = [
    "Ledna",
    "Února",
    "Března",
    "Dubna",
    "Května",
    "Června",
    "Července",
    "Srpna",
    "Září",
    "Října",
    "Listopadu",
    "Prosince",
];

export const DAYS_CZECH = ["Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek", "Sobota", "Neděle"];
